DROP DATABASE IF EXISTS RENT_DOG;
CREATE DATABASE RENT_DOG;

USE RENT_DOG;

/*Customer table*/
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
	CUSTOMER_ID				INT AUTO_INCREMENT
,	CUSTOMER_FIRST_NAME		VARCHAR(50) NOT NULL
,	CUSTOMER_LAST_NAME		VARCHAR(100) NOT NULL
,	CUSTOMER_EMAIL			VARCHAR(100) NOT NULL
,	CUSTOMER_DOB			DATE NOT NULL
,	CUSTOMER_PASSWORD		VARCHAR(250) NOT NULL
,	CUSTOMER_STREET_ADDRESS	VARCHAR(200) NOT NULL
,	CUSTOMER_CITY			VARCHAR(100) NOT NULL
,	CUSTOMER_PROVINCE		VARCHAR(100) NOT NULL
,	CUSTOMER_POSTAL_CODE	VARCHAR(6) NOT NULL
,	CUSTOMER_PHONE_NUMBER	VARCHAR(13) NOT NULL
,	CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (CUSTOMER_ID)
);

/*Dog table*/
DROP TABLE IF EXISTS DOGGO;
CREATE TABLE DOGGO (
	DOGGO_ID				INT AUTO_INCREMENT
,	CUSTOMER_ID				INT NOT NULL
,	DOGGO_NAME				VARCHAR(100) NOT NULL
,	DOGGO_BREED				VARCHAR(100) NOT NULL
,	DOGGO_SIZE				VARCHAR(50) NOT NULL
,	DOGGO_DESCRIPTION		VARCHAR(500) NOT NULL
,	DOGGO_AVAILABILITY		VARCHAR(20) NOT NULL
,	DOGGO_PRICE_PER_HOUR	DECIMAL(10,2) NOT NULL
,	CONSTRAINT PK_DOGGO_ID PRIMARY KEY (DOGGO_ID)
,	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

/*Contract table*/
DROP TABLE IF EXISTS CONTRACT;
CREATE TABLE CONTRACT (
	CONTRACT_ID				INT AUTO_INCREMENT
,	CUSTOMER_ID				INT NOT NULL
,	DOGGO_ID				INT NOT NULL
,	CONTRACT_CREATE_DATE	DATETIME
,	CONTRACT_RENT_DATE		DATE
,	CONTRACT_STARTED_OWNER	DATETIME
,	CONTRACT_STARTED_RENTER	DATETIME
,	CONTRACT_ENDED_OWNER	DATETIME
,	CONTRACT_ENDED_RENTER	DATETIME
,	CONSTRAINT PK_C_CONTRACT_ID PRIMARY KEY (CONTRACT_ID)
,	FOREIGN KEY FK_C_CUSTOMER_ID (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
,	FOREIGN KEY FK_C_DOGGO_ID (DOGGO_ID) REFERENCES DOGGO (DOGGO_ID)
);